add extra step to waiting fo BookShop Project Compile finish

diff --git a/.github/workflows/bookshop-admin.build.yml b/.github/workflows/bookshop-admin.build.yml
--- a/.github/workflows/bookshop-admin.build.yml
+++ b/.github/workflows/bookshop-admin.build.yml
@@ -30,6 +30,13 @@ jobs:
           distribution: "temurin"
           java-version: "17"
           cache: maven
+      
+      # pending on waiting for BookShop Project CI/CD Pipeline Finish && Success 
+      - name: Wait for BookShop Project Build and Compile Success
+        if: ${{ github.event.workflow_run.conclusion != 'success' }}
+        run: |
+          echo "Previous BookShop Project CI/CD failed or did not complete successfully."
+          exit 1
 
       - name: Build Project
         run: cd bookshop-admin && mvn clean package -DskipTests
